main: main.o
	g++ main.o -o main ../vendor/libpngCYG/lib/libpng.a ../vendor/zlibCYG/lib/libz.a 
	rm main.o

main.o: main.cc
	g++ -c main.cc -I../vendor/png++-0.2.9/ -I../vendor/libpngCYG/include/libpng16/